application:
    build: notification/code
    volumes:
        - ../:/var/www/notification
        - logs/app/:/var/www/notification/app/logs
    tty: true

mariadb:
    build: notification/mariadb
    ports:
        - 3308:3306
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=notification
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root

php:
    build: notification/php
    ports:
        - 9000:9000
        - 9001:9001
    volumes:
        - logs/php/:/var/log/php
    volumes_from:
        - application
    links:
        - mariadb
    environment:
        - PHP_SECRET=sjoidf9763klmdflfoegfihk676430jjghuj876vbth543

nginx:
    build: notification/nginx
    ports:
        - 1337:1337
        - 8081:80
        - 8082:443
    links:
        - php
    volumes_from:
        - application
    volumes:
        - logs/nginx/:/var/log/nginx
