security:
    providers:
        in_memory:
             memory:
                users:
                    user1:  { password: password, roles: 'ROLE_USER' }
                    user2: { password: password, roles: 'ROLE_USER' }
                    user3: { password: password, roles: 'ROLE_USER' }
                    user4: { password: password, roles: 'ROLE_ADMIN' }
                    user5: { password: password, roles: 'ROLE_USER' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check

            logout:
                path:   /logout
                target: /app/example