watcher_notify:
    channel: watcher
    handler:
        callback: 'prophet777.watcher.topic'
    requirements:
        type:
            pattern: debug|info|notice|error|emergency
            wildcard: true