services:
    gos_notification.notification_center:
        class: Gos\Bundle\NotificationBundle\NotificationCenter
        arguments:
            - @snc_redis.notification
            - @?monolog.logger.notification

    gos_notification.notification.pubsub.server:
        class: Gos\Bundle\NotificationBundle\Server\PubSubServer
        arguments:
            - @event_dispatcher
            - %gos_notification.notification_class%
            - %gos_notification.notification_context_class%
            - @gos_notification.pusher.registry
            - %gos_notification.pubsub_server.config%
            - @?monolog.logger.notification
        tags:
            - { name: gos_web_socket.server }

    gos_notification.notification.listener:
        class: Gos\Bundle\NotificationBundle\Listener\NotificationListener

    gos_notification.user.topic:
        class: Gos\Bundle\NotificationBundle\Topic\UserNotificationTopic
        tags:
            - { name: gos_web_socket.topic }

    gos_notification.pusher.registry:
        class: Gos\Bundle\NotificationBundle\Pusher\PusherRegistry

    gos_notification.pusher.redis:
        class: Gos\Bundle\NotificationBundle\Pusher\RedisPusher
        arguments:
            - 127.0.0.1
            - 6379
#        tags:
#            - { name: gos_notification.pusher }

    gos_notification.pusher.websocket:
        class: Gos\Bundle\NotificationBundle\Pusher\WebsocketPusher
        arguments:
            - %web_socket_server.host%
            - %web_socket_server.port%
#        tags:
#            - { name: gos_notification.pusher }

    gos_notification.fetcher.redis:
        class: Gos\Bundle\NotificationBundle\Fetcher\RedisFetcher

