user_notification_websocket:
    channel: notification/user/{username}
    handler:
        callback: 'gos.notification.topic'
    requirements:
        username:
            pattern: "[a-zA-Z0-9]+"
            wildcard: true
